version: "3.9"
   
services:
  web:
    build: .
    container_name: mvdk-backend-aai-test
    image: ghcr.io/mediatheken-vernetzen/mvdk-backend-aai-test-0.1
    command: >
      bash -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && gunicorn mvdk_backend_aai_test.wsgi:application --bind 0.0.0.0:8080 --access-logfile - --log-level debug"
    ports:
      - "8084:8080"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
