name: mvdk_backend AAI test

env:
  IMAGE_TAG: mvdk-backend-aai-test
  IMAGE_VERSION: 0.1

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            ghcr.io/mediatheken-vernetzen/${{ env.IMAGE_TAG }}-${{ env.IMAGE_VERSION }}
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

  deploy_main:
    needs: build
    name: Deploy to test environment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1.3.0
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'mvdk-backend-aai-test'
          stack-definition: 'docker-compose.yml'
          image: ghcr.io/mediatheken-vernetzen/${{ env.IMAGE_TAG }}-${{ env.IMAGE_VERSION }}
